### ISSUE TITLE
Eth can no longer be mined, should switch to a Proof of work coin.

### ISSUE THREAD

**Issue by narstybits** [grugnoymeme/flipperzero-badUSB#4]
The Ethereum script is very nice, the idea is even better! As far as I know, since the Eth 2.0 upgrade to Proof Of Stake Eth can no longer be mined via computational power. It now uses proof of stake consensus to validate transactions and create new blocks. 
There are still alot of POW proof of work coins and I think you can make the script versatile enough to allow different coin inputs while keeping the same boilerplate.

Or you could just switch it to ethereum classic (ETC) it still uses proof of work! 

Take care friend

**Comment by grugnoymeme** [comment]
Thank u very much for the gupdate :) i'll modify soon to make it work perfectly.
See you!!!

**Comment by grugnoymeme** [comment]
If u want you can also modify my code and open pull request to become collaborator :) it would be great

**Comment by narstybits** [comment]
Okay sounds good! If I see something in the future I will first submit an issue and then if you are okay with it I'll do the PR!
